# all:
#   exclude:
#     - "spec/**/*"
# exclude files for single runner
# eslint:
#   exclude:
#     - "app/assets/**/*"
# github:
#   slug: prontolabs/pronto
#   access_token: B26354
#   api_endpoint: https://api.github.com/
#   web_endpoint: https://github.com/
# gitlab:
#   slug: 1234567 # gitlab's project ID
#   api_private_token: 46751
#   api_endpoint: https://api.vinted.com/gitlab
# bitbucket:
#   slug: prontolabs/pronto
#   username: user
#   password: pass
#   web_endpoint: https://bitbucket.org/
# max_warnings: 150
# verbose: true
