# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
FCLUB_EMAIL_USERNAME: 'fclub.framgia.info@gmail.com'
FCLUB_EMAIL_PASSWORD: 'framgiadn2017'
DEFAULT_URL: 'http://club.framgia.vn'
APP_ID: 'HMCxTc2b5A53vqhQqj2Apciz'
APP_SECRET: '93f72bf41fb1079febfe80a0ac4674c7f361ea64013faf190d2cb3a2bc7b'
